/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ZenRuntime {
  constructor(options: JsRuntimeOptions, logger?: JsLogTsfn | undefined | null)
  registerQueue(options: JsQueueOptions, handler: JsHandlerTsfn): void
  registerSchedule(options: JsScheduleOptions, handler: JsHandlerTsfn): void
  registerWorkflow(options: JsWorkflowOptions, executor: JsExecutorTsfn): void
  registerMachine(options: JsMachineOptions): void
  /** Create a machine instance in its initial state. False = existed. */
  machineCreate(machine: string, id: string): boolean
  /** Apply an event; returns JSON { from, to }. Invalid transitions throw. */
  machineSend(machine: string, id: string, event: string): string
  machineState(machine: string, id: string): string | null
  /** History as a JSON array (newest first). */
  machineHistory(machine: string, id: string, limit?: number | undefined | null): string
  /** Sync trigger (hot path). Returns the run id. */
  triggerWorkflow(workflow: string, input: string, options?: JsTriggerOptions | undefined | null): string
  /** Sync step recording (hot path — called once per completed step). */
  recordStep(runId: string, stepId: string, kind: string, result?: string | undefined | null): void
  /** Runtime metrics counters as JSON (P3.11). */
  metricsSnapshot(): string
  /** Run a retention GC pass now; returns `{ runs, steps, events }` JSON (P7.6). */
  runGc(): string
  /** Readiness: started AND the store answers a ping (P7.7). */
  healthCheck(): boolean
  /** Agent session conversation JSON, or null (P4.7). */
  agentSessionGet(agent: string, id: string): string | null
  agentSessionPut(agent: string, id: string, messages: string): void
  /**
   * Sync event emit through the atomic outbox. Returns JSON
   * { woken, triggered }.
   */
  emitEvent(event: string, payload: string): string
  dashboardRuns(workflow?: string | undefined | null, status?: number | undefined | null, limit?: number | undefined | null): Promise<string>
  dashboardRunSteps(runId: string): Promise<string>
  dashboardQueues(): Promise<string>
  dashboardSchedules(): Promise<string>
  dashboardEvents(limit?: number | undefined | null): Promise<string>
  /** Run row as JSON, or null when unknown. */
  getRun(runId: string): string | null
  /** Wait until the run is terminal (or timeout). Async is fine — long wait. */
  waitForRun(runId: string, timeoutMs: number): Promise<string | null>
  /** Cancel a run and its descendants. Returns the number cancelled. */
  cancelRun(runId: string): number
  start(): void
  /** Sync push (hot path). Returns the job id. */
  push(queue: string, payload: string, options?: JsPushOptions | undefined | null): string
  pushBulk(queue: string, payloads: Array<string>, options?: JsPushOptions | undefined | null): Array<string>
  /**
   * Graceful shutdown; returns true if all in-flight jobs drained within
   * the timeout. Async NAPI is fine here — cold path.
   */
  stop(timeoutMs?: number | undefined | null): Promise<boolean>
  pendingCount(queue: string): Promise<number>
  activeCount(queue: string): Promise<number>
  /** Dead-letter jobs as a JSON string (parsed JS-side). */
  deadJobs(queue: string, limit?: number | undefined | null): Promise<string>
  requeueDead(ids: Array<string>): Promise<number>
  /** Pause a queue: stop claiming new jobs on this node (P14.1). */
  pauseQueue(queue: string): void
  /** Resume a paused queue. */
  resumeQueue(queue: string): void
  isQueuePaused(queue: string): boolean
  /** Bulk control-plane op (P14.1): delete all dead-lettered jobs for a queue. */
  purgeDead(queue: string): Promise<number>
}

export declare function asyncAdd(a: number, b: number): Promise<number>

export declare function asyncEchoBuffer(input: Buffer): Promise<Buffer>

export declare function benchSqliteQueue(path: string, jobs: number): SqliteBenchResult

/**
 * Pipelined round-trips in waves of `concurrency`. Models many concurrent
 * workflow runs invoking JS handlers at once.
 */
export declare function benchTsfnConcurrent(tsfn: ((err: Error | null, arg: number) => number), iterations: number, concurrency: number): Promise<number>

/**
 * Sequential round-trips: Rust awaits the JS return value each iteration.
 * Models "engine invokes a JS step handler and waits for the result".
 */
export declare function benchTsfnRoundtrip(tsfn: ((err: Error | null, arg: number) => number), iterations: number): Promise<number>

/** One execution attempt request handed to the JS executor. */
export interface JsExecRequest {
  runId: string
  workflow: string
  /** JSON input. */
  input: string
  version?: string
  /** JSON array of completed steps: [{ id, kind, result }]. */
  journal: string
}

export interface JsJob {
  id: string
  queue: string
  /** JSON-encoded payload. */
  payload: string
  attempt: number
  maxAttempts: number
}

export interface JsLogEvent {
  /** ERROR | WARN | INFO | DEBUG | TRACE */
  level: string
  /** Rust module path, e.g. "zenzip_core::queue". */
  target: string
  message: string
}

export interface JsMachineOptions {
  name: string
  initial: string
  transitions: Array<JsTransition>
}

export interface JsPushOptions {
  delayMs?: number
  priority?: number
  maxAttempts?: number
  /** Per-key concurrency bucket for this job (P10.1). */
  concurrencyKey?: string
  /** Debounce bucket for this job (P10.2). */
  debounceKey?: string
  /** Throttle bucket + spacing (ms) for this job (P10.2). */
  throttleKey?: string
  throttleSpacingMs?: number
}

export interface JsQueueOptions {
  name: string
  concurrency?: number
  maxAttempts?: number
  backoffDelayMs?: number
  backoffMaxDelayMs?: number
  leaseMs?: number
  pollMs?: number
  batch?: number
  /** Jobs per handler invocation (1 = per-job consumer). */
  handlerBatch?: number
  rateLimitMax?: number
  rateLimitPerMs?: number
  /** Per-key concurrency limit (P10.1). */
  concurrencyKeyLimit?: number
  /** Fairness across concurrency-key groups (P10.3). */
  fair?: boolean
}

export interface JsRuntimeOptions {
  dataDir: string
  /** When set, use the Postgres backend (P5) instead of embedded SQLite. */
  postgresUrl?: string
  sweepMs?: number
  schedulerTickMs?: number
  workerThreads?: number
  /** error | warn | info | debug | trace | off (default: off) */
  logLevel?: string
  /** Retention GC sweep cadence in ms (P7.6). Default: 1h. */
  gcSweepMs?: number
  /** Delete terminal runs older than this (ms). <= 0 disables. Default: 7d. */
  runRetentionMs?: number
  /** Delete events older than this (ms). <= 0 disables. Default: 7d. */
  eventRetentionMs?: number
  /** Payload encryption-at-rest passphrase (P7.15). Unset/empty = disabled. */
  encryptionKey?: string
}

export interface JsScheduleOptions {
  name: string
  /** Exactly one of `cron` / `everyMs` must be set. */
  cron?: string
  everyMs?: number
  timezone?: string
  /** skip | allow | queue (default skip) */
  overlap?: string
  /** skip | runOnce | all (default skip) */
  catchup?: string
  /** Random 0..=jitterMs delivery delay per fire. */
  jitterMs?: number
}

export interface JsTransition {
  from: string
  event: string
  to: string
}

export interface JsTriggerOptions {
  idempotencyKey?: string
  delayMs?: number
}

export interface JsWorkflowOptions {
  name: string
  /** Content hash of the definition (P2.11 version pinning). */
  version?: string
  concurrency?: number
  /** Total step attempts (retries + 1). */
  stepMaxAttempts?: number
  stepBackoffDelayMs?: number
  stepBackoffMaxDelayMs?: number
  /** Execution-attempt lease (crash redelivery horizon). */
  leaseMs?: number
  /** Event patterns that durably trigger this workflow (P3.2). */
  triggers?: Array<string>
}

export interface SqliteBenchResult {
  jobs: number
  insertMs: number
  claimAckMs: number
  insertOpsPerSec: number
  claimAckOpsPerSec: number
}

/**
 * Rust accepts the connection, JS produces the response body via TSFN.
 * This is the architecture under evaluation in D5 (Rust HTTP go/no-go).
 */
export declare function startHyperJs(port: number, handler: ((err: Error | null, arg: string) => string)): void

/** Pure-Rust hello-world server: the upper bound (no JS involved). */
export declare function startHyperStatic(port: number): void

export declare function syncAdd(a: number, b: number): number

export declare function syncEchoBuffer(input: Buffer): Buffer

export declare function syncJsonParseStringify(input: string): string

export declare function syncNoop(): void
