/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function asyncAdd(a: number, b: number): Promise<number>

export declare function asyncEchoBuffer(input: Buffer): Promise<Buffer>

export declare function benchSqliteQueue(path: string, jobs: number): SqliteBenchResult

/**
 * Pipelined round-trips in waves of `concurrency`. Models many concurrent
 * workflow runs invoking JS handlers at once.
 */
export declare function benchTsfnConcurrent(tsfn: ((err: Error | null, arg: number) => number), iterations: number, concurrency: number): Promise<number>

/**
 * Sequential round-trips: Rust awaits the JS return value each iteration.
 * Models "engine invokes a JS step handler and waits for the result".
 */
export declare function benchTsfnRoundtrip(tsfn: ((err: Error | null, arg: number) => number), iterations: number): Promise<number>

export interface SqliteBenchResult {
  jobs: number
  insertMs: number
  claimAckMs: number
  insertOpsPerSec: number
  claimAckOpsPerSec: number
}

/**
 * Rust accepts the connection, JS produces the response body via TSFN.
 * This is the architecture under evaluation in D5 (Rust HTTP go/no-go).
 */
export declare function startHyperJs(port: number, handler: ((err: Error | null, arg: string) => string)): void

/** Pure-Rust hello-world server: the upper bound (no JS involved). */
export declare function startHyperStatic(port: number): void

export declare function syncAdd(a: number, b: number): number

export declare function syncEchoBuffer(input: Buffer): Buffer

export declare function syncJsonParseStringify(input: string): string

export declare function syncNoop(): void
