import type { Metadata } from "next";

import { CodeBlock } from "@/components/code-block";
import { DocPage } from "@/components/docs/doc-page";
import {
  A,
  Callout,
  Code,
  H2,
  LI,
  P,
  Strong,
  Table,
  UL,
} from "@/components/docs/typography";

export const metadata: Metadata = {
  title: "Concepts",
  description:
    "The ZenZip mental model: one engine under queues, workflows, agents, and machines — the vocabulary, the app lifecycle, and which primitive to reach for.",
  alternates: { canonical: "/docs/concepts" },
  openGraph: {
    title: "Concepts · ZenZip",
    description:
      "The ZenZip mental model: one engine under queues, workflows, agents, and machines — the vocabulary, the app lifecycle, and which primitive to reach for.",
    url: "/docs/concepts",
    type: "article",
  },
};

const toc = [
  { id: "one-engine", title: "One engine" },
  { id: "vocabulary", title: "Vocabulary" },
  { id: "which", title: "Which primitive?" },
  { id: "lifecycle", title: "App lifecycle" },
  { id: "guarantees", title: "Guarantees at a glance" },
  { id: "where-state", title: "Where state lives" },
];

const lifecycle = `import { zenzip } from "zenzipjs";

const app = zenzip();              // 1. construct — no I/O yet

const q = app.queue("emails");     // 2. DEFINE phase: register everything
q.process(async (job) => { ... }); //    queues, workflows, agents, schedules,
app.workflow("order", fn);         //    machines, routes — all before start()

await app.start();                 // 3. START: open store, run migrations,
                                   //    boot the Rust engine + dispatchers

await q.push({ to });              // 4. RUNTIME: push / trigger / emit / send
await app.listen({ port: 3000 });  //    from anywhere

await app.stop({ timeout: "30s" });// 5. STOP: stop claiming, drain in-flight,
                                   //    close the store (idempotent)`;

export default function Page() {
  return (
    <DocPage
      title="Concepts"
      description="The mental model in one page: one engine underneath everything, the vocabulary you'll meet, and which primitive to reach for."
      href="/docs/concepts"
      toc={toc}
    >
      <H2 id="one-engine">One engine underneath everything</H2>
      <P>
        ZenZip has exactly <Strong>one execution engine</Strong>. Every feature
        you use is a projection of it, which is why they all share the same
        crash recovery, retries, and observability:
      </P>
      <Table
        head={["You write", "Underneath, it's…"]}
        rows={[
          [<Code key="1">app.queue().process()</Code>, "leased, retryable units of work — the engine itself"],
          [<Code key="2">app.schedule()</Code>, "a timer that enqueues onto a hidden queue when it fires"],
          [<Code key="3">app.workflow()</Code>, "a run whose handler drives a step journal"],
          [<Code key="4">app.agent()</Code>, "a workflow whose steps are generated by an LLM loop"],
          [<Code key="5">app.machine()</Code>, "a guarded row + an event emitted on every transition"],
        ]}
      />
      <P>
        Recovery is implemented once. The same lease sweep that redelivers a
        crashed queue job resumes a crashed workflow and a crashed agent. The{" "}
        <A href="/docs/architecture">Architecture</A> page goes a level
        deeper; this page is the map.
      </P>

      <H2 id="vocabulary">Vocabulary</H2>
      <P>The words that show up across the docs, the dashboard, and errors:</P>
      <Table
        head={["Term", "Meaning"]}
        rows={[
          [<Strong key="1">Job</Strong>, "One unit of queued work. Has a payload, attempt count, and (while claimed) a lease."],
          [<Strong key="2">Lease</Strong>, "A time-bound claim on a job/run. If the worker dies, the lease expires and the work is redelivered — this is how crashes recover."],
          [<Strong key="3">Run</Strong>, "One execution of a workflow or agent. Has a status (running, sleeping, waitingEvent, waitingChild, completed, failed, cancelled)."],
          [<Strong key="4">Step</Strong>, "A durable unit inside a run (step.run / sleep / waitForEvent / invoke). Its result is journaled."],
          [<Strong key="5">Journal</Strong>, "The recorded results of a run's completed steps. On retry/resume the run fast-forwards through it instead of re-executing."],
          [<Strong key="6">Memoization</Strong>, "Returning a step's journaled result instead of running it again. The core of durability (and why tool failures don't re-prompt the model)."],
          [<Strong key="7">DLQ</Strong>, "Dead-letter queue: where a job lands after exhausting its retry budget. Inspect and requeue it."],
          [<Strong key="8">Outbox</Strong>, "The atomic event log: emit persists the event, wakes waiters, and creates triggered runs in one transaction."],
          [<Strong key="9">Idempotency key</Strong>, "A caller-supplied key that dedupes run creation — the same key never starts two runs."],
        ]}
      />

      <H2 id="which">Which primitive do I reach for?</H2>
      <Table
        head={["I want to…", "Use", "Guide"]}
        rows={[
          ["run background work, retried on failure", <Code key="1">app.queue()</Code>, <A key="a" href="/docs/queues">Queues</A>],
          ["do something on a clock", <Code key="2">app.schedule()</Code>, <A key="b" href="/docs/schedules">Schedules</A>],
          ["orchestrate multi-step work that must survive crashes", <Code key="3">app.workflow()</Code>, <A key="c" href="/docs/workflows">Workflows</A>],
          ["wait for an external signal or human action mid-process", <Code key="4">step.waitForEvent()</Code>, <A key="d" href="/docs/events">Events</A>],
          ["build an LLM agent with tools", <Code key="5">app.agent()</Code>, <A key="e" href="/docs/agents">Agents</A>],
          ["enforce a valid lifecycle for an entity", <Code key="6">app.machine()</Code>, <A key="f" href="/docs/state-machines">State Machines</A>],
          ["fan a signal out to many consumers", <Code key="7">app.emit()</Code> , <A key="g" href="/docs/events">Events</A>],
          ["expose HTTP / receive webhooks", <Code key="8">app.get()</Code> , <A key="h" href="/docs/http-dashboard">HTTP</A>],
        ]}
      />
      <Callout type="tip" title="Rule of thumb">
        <p>
          If the work is <strong>one shot</strong>, it&apos;s a queue job. If it
          has <strong>steps, waits, or sleeps</strong> that must survive a
          restart, it&apos;s a workflow. If those steps are{" "}
          <strong>chosen by a model</strong>, it&apos;s an agent.
        </p>
      </Callout>

      <H2 id="lifecycle">App lifecycle</H2>
      <P>
        Every app moves through the same phases. The key rule:{" "}
        <Strong>define before start</Strong> — registering a queue, workflow,
        agent, machine, or route after <Code>start()</Code> throws.
      </P>
      <CodeBlock code={lifecycle} filename="lifecycle.ts" className="mt-6" />

      <H2 id="guarantees">Guarantees at a glance</H2>
      <Table
        head={["Thing", "Guarantee"]}
        rows={[
          ["Queue & run delivery", "at-least-once"],
          ["Step result recording", "effectively-once (a completed entry is never overwritten)"],
          ["Step side effects", "at-least-once (make external effects idempotent)"],
          ["Run creation with idempotencyKey", "exactly-once per key"],
          ["State machine transition + its event", "atomic (one transaction)"],
          ["Event outbox (emit → waiters + triggers)", "atomic (one transaction)"],
        ]}
      />
      <P>
        The full contract — including the step-memoization model, versioning
        rules, and the idempotency guide — is on{" "}
        <A href="/docs/durability">Durability &amp; Semantics</A>.
      </P>

      <H2 id="where-state">Where state lives</H2>
      <UL>
        <LI>
          <Strong>Default:</Strong> one SQLite file (WAL mode) in your{" "}
          <Code>dataDir</Code> (<Code>.zenzip/zenzip.db</Code>). Jobs,
          schedules, runs, the step journal, events, machines, and agent
          sessions all live there. Inspect it with any SQLite client; back it
          up by copying the file.
        </LI>
        <LI>
          <Strong>Multi-node:</Strong> point at Postgres with one config line
          (<Code>{`store: { driver: "postgres", url }`}</Code>). Same API,
          same semantics — claims use <Code>SKIP LOCKED</Code>, nodes wake
          each other via <Code>LISTEN/NOTIFY</Code>. See{" "}
          <A href="/docs/configuration">Configuration</A>.
        </LI>
        <LI>
          <Strong>Nothing in memory that matters.</Strong> A suspended
          workflow, a scheduled tick, a pending approval — all are rows. Kill
          the process and they survive.
        </LI>
      </UL>
    </DocPage>
  );
}
